services:
  - type: web
    name: discord-bot-backend
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    healthCheckPath: /api/health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        value: https://heroic-trifle-017002.netlify.app
      - key: PORT
        value: 5000